# wrangler.toml

name = "moboy-earn" # Ganti dengan nama aplikasi Anda
compatibility_date = "2024-10-23" # Tanggal kompatibilitas, bisa dibiarkan seperti ini
pages_build_output_dir = ".open-next" # ini untuk menghilangkan peringatan
# compatibility_flags = ["nodejs_compat"] # Hapus komentar jika Anda memerlukan kompatibilitas Node.js

# [vars]
# MY_VARIABLE = "my_value" # Definisikan environment variable di sini jika diperlukan
