name = "moboy-earn"
compatibility_date = "2024-10-23"

# SANGAT PENTING: Aktifkan kompatibilitas Node.js
# Ini memungkinkan penggunaan API Node.js (seperti crypto, buffer, dll.)
# yang dibutuhkan oleh Next.js dan dependencies seperti NextAuth.
compatibility_flags = ["nodejs_compat"]

# Tentukan folder output dari build OpenNext
pages_build_output_dir = ".open-next"
