name = "moboy-earn"
compatibility_date = "2024-10-23"

# Konfigurasi untuk Pages
pages_build_output_dir = ".open-next"

# Format yang BENAR untuk compatibility_flags
compatibility_flags = ["nodejs_compat"]

# ... konfigurasi lainnya jika ada
